# Generated by Django 5.0 on 2024-02-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_slider_alter_contactformmessage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='promotion1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='promotion2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='promotion3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='promotion4',
            field=models.TextField(blank=True),
        ),
    ]
