# Generated by Django 5.0 on 2024-03-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_slider_promotion1_slider_promotion2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
