# Generated by Django 5.0 on 2024-03-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_categories_level_categories_lft_categories_rght_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.CharField(choices=[('True', 'Evet'), ('False', 'Hayir')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
