# Generated by Django 5.0 on 2024-03-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0009_product_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new',
            field=models.CharField(choices=[('True', 'Evet'), ('False', '(Hayir')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
