# Generated by Django 5.0.1 on 2024-03-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0010_product_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kampaniya',
            field=models.CharField(choices=[('True', 'Evet'), ('False', 'Hayir')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
