# Generated by Django 5.0 on 2024-03-15 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0011_product_kampaniya'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='popular',
            field=models.CharField(choices=[('True', 'Evet'), ('False', 'Hayir')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
