# Generated by Django 5.0 on 2024-05-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0013_alter_product_new_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='status',
            field=models.CharField(choices=[('True', 'Evet'), ('False', 'Hayir')], max_length=100),
        ),
    ]
